version: '3'

services:
  api:
    build: .
    container_name: api-rest-container
    restart: always
    volumes:
        - ./:/home/node/app
    ports:
      - "7070:7070"
    command: node server.js